name: Get Posts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    env:
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn install

      - name: Run Script
        run: ts-node scripts/get-posts
